SELECT 
    SITUACAO_CADASTRAL ,COUNT(CNPJ) AS "TOTAL ESTABELECIMENTOS" 
FROM 
    tb_rfb
GROUP BY 
    SITUACAO_CADASTRAL;
    
SELECT * FROM receita LIMIT 5;

SELECT 
        RFB.CNPJ AS CNPJ,
        RFB.RAZAO_SOCIAL AS RAZAO_SOCIAL_RFB,
        RFB.NOME_FANTASIA AS NOME_FANTASIA,
        RFB.CEP AS CEP,
        RFB.ENDERECO AS ENDERECO,
        RFB.BAIRRO AS BAIRRO,
        RFB.CIDADE AS CIDADE,
        RFB.UF AS UF,
        RFB.TELEFONE AS TELEFONE,
        RFB.EMAIL AS "E-MAIL",
        RFB.CNAE_PRINCIPAL AS CNAE_PRINCIPAL,
        RFB.CNAE_DESCRICAO AS CNAE_DESCRICAO,
        RFB.CNAE_SECUNDARIO AS CNAE_SECUNDARIO,
        RFB.SITUACAO_CADASTRAL AS SITUACAO_CADASTRAL,
        strftime(
            '%d/%m/%Y', date(
                RFB.DATA_INICIO_ATIVIDADE
            )
        ) AS DATA_INICIO_ATIVIDADE,
        strftime(
            '%d/%m/%Y',date(
                RFB.DATA_SITUACAO_CADASTRAL
            )
        ) AS DATA_SITUACAO_CADASTRAL
    FROM tb_rfb RFB
LIMIT 5;

SELECT * FROM TB_CACHE;
DROP TABLE TB_CACHE;
DROP VIEW RECEITA;

SELECT DISTINCT(SITUACAO_CADASTRAL) FROM TB_RFB;

